# Generated by Django 5.0.4 on 2025-01-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_dealer_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
    ]
